# coding: utf-8

"""
    stylelens_detector_sdk

    This is a API document for Object Detection on fashion items\"

    OpenAPI spec version: 0.0.1
    Contact: devops@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import bluelens_search
from bluelens_search.rest import ApiException
from bluelens_search.models.detect_objects_response import DetectObjectsResponse


class TestDetectObjectsResponse(unittest.TestCase):
    """ DetectObjectsResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetectObjectsResponse(self):
        """
        Test DetectObjectsResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = bluelens_search.models.detect_objects_response.DetectObjectsResponse()
        pass


if __name__ == '__main__':
    unittest.main()
